# .github/workflows/deploy.yml
on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      flg:
        required: false
        type: string
        default: "false"
    secrets:
      TOKEN:
        required: true
      JSON:
        required: false

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          FLG="${{ inputs.flg }}"
          if [ "$FLG" = "true" ]; then
            # echo "flg is true!!"
          else
            # echo "flg is not true!!"
          fi
