name: Sample Composite
inputs:
  parameter1:
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: composite hello
      shell: bash
      run: |
        echo "hello composite"
        echo "parameter1: ${{ inputs.parameter1 }}"
