name: Sample Composite
runs:
  using: "composite"
  steps:
    - name: composite hello
      shell: bash
      run: |
        echo "hello composite"
        echo "ORG_SECRET: ${{ secrets.ORG_SECRET }}"
